name: Create QA-deployment Infra PR

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Buildkite Build Number (e.g. 1234)'
        required: true
      qa_env:
        type: choice
        description: Environment
        required: true
        options: 
        - staging
        - qa-berlin
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Edit build number & push change
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       BUILD_NO=${{ github.event.inputs.build_number }}
       QA_ENV=${{ github.event.inputs.qa_env }}
        if [ $QA_ENV == staging ]; then
          PR_BUILD_LABEL="Staging release build to ${BUILD_NO}"
          APP_PATH=lilly-app
        else
          PR_BUILD_LABEL="QA build to ${BUILD_NO}"
          APP_PATH=lilly-app/qa/$QA_ENV
        fi
        
        BRANCH_NAME="lilly-app-${QA_ENV}-build-to-${BUILD_NO}"
        PR_LABEL="[lilly-app/${QA_ENV}] Update ${PR_BUILD_LABEL}"
        PR_EXISTS=$(gh pr list | grep $PR_LABEL | wc -l | xargs)
        BRANCH_EXISTS=$(git ls-remote --heads origin $BRANCH_NAME | wc -l | xargs)
        
        PRs=$(gh pr list | search "title:$PR_LABEL" | wc -l)
        echo "${PRs}"
        echo "${PRs}[0]"

        echo "## VARIABLES"
        echo "PR_LABEL: ${PR_LABEL}"
        echo "BRANCH_NAME: ${BRANCH_NAME}"
        echo "PR_EXISTS: ${PR_EXISTS}"
        echo "BRANCH_EXISTS: ${BRANCH_EXISTS}"
        
        git fetch
        git checkout -b $BRANCH_NAME
        
        sed -i 's/\(image: haha\/frontend\/build:\).*$/\1'"$BUILD_NO"'/' test.yml
        
        git config --global user.email "thanthtetzin1990@gmail.com"
        git config --global user.name "thanthtetzin"
        
        git add .
        git commit -m "Update build number to $BUILD_NO"

        if [ $BRANCH_EXISTS == 0 ]; then
          git push --set-upstream origin $BRANCH_NAME
        else
          git push
        fi
        
         if [ $PR_EXISTS == 0 ]; then
          echo "Opening new PR"
          NEW_PR=gh pr create --title "$PR_LABEL" --body "Update build for \`lillyapp\` / \`$QA_ENV\` environment\nhttps://hello.com/$BUILD_NO"
          echo "$NEW_PR"
        else
          echo "Updating pre-existing PR"
        fi
